sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - sudo setcap 'cap_net_bind_service=+ep' `which node`
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone --branch=develop https://github.com/reTHINK-project/dev-hyperty.git ~/build/reTHINK-project/dev-hyperty
  - export HYPERTY_REPO=./dev-hyperty

install:
  - npm install
  - npm run start:browser &
  - sleep 60
