sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
  - nvm use system
  - sudo setcap 'cap_net_bind_service=+ep' `which node`
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git clone --branch=develop https://github.com/reTHINK-project/dev-hyperty.git
  - git clone --branch=develop https://github.com/reTHINK-project/dev-hyperty-toolkit.git
  - export HYPERTY_REPO=./dev-hyperty
  - cd dev-hyperty-toolkit

install:
  - npm install
  - sudo npm run start:browser &
  - sleep 60
